### ISSUE TITLE
build_config

### ISSUE THREAD

**Issue by jjkakakk** [wirepair/twurle#1]
build_config line 40 single quote
 ... perl -p -i -e "s/secret.\'/secret.\"/;" ./build_config.py

also think maybe config={} should be defined before use?

cheers

**Comment by wirepair** [comment]
you are correct, sorry looks like the twitter package has been updated and 'Status' is no longer supported. I'll work on updating this to work again soon.

**Comment by wirepair** [comment]
ok just tried updating it and the python-twitter api is total crap. I'd probably have to rewrite using the real twitter api.
