### ISSUE TITLE
Future of twurle

### ISSUE THREAD

**Issue by cmluciano** [wirepair/twurle#2]
I am very interested in this project and was wondering if you are rewriting a supported version in a different language. If not I'd like to reboot it in node if that's cool with you.

**Comment by wirepair** [comment]
So i've rewritten it in Go lang but i haven't had time to support creating the application yourself using the twitter api which is why i haven't released it. By all means reboot it in node, maybe you can build a better UI then than one i built :>.

**Comment by cmluciano** [comment]
Ah, no sense duping the work then. I'd certainly be interested in assisting with this project if you'd like though. I could even just contribute some work the front-end.

**Comment by wirepair** [comment]
Cool yeah, uh over the weekend I'll try to push what I have and open it up a bit, the UI is a bit broken and doesn't contain adding the app via the twitter API. However I still use it daily (just run as a background process) to snarf tweets with urls, even the limited functionality i have is extremely helpful.
